---
development:
  cloud_name: hdxqvjx8d
  api_key: '226391955645232'
  api_secret: mM68VrokMFI-EzeTwGWh-x9HUnI
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: hdxqvjx8d
  api_key: '226391955645232'
  api_secret: mM68VrokMFI-EzeTwGWh-x9HUnI
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: hdxqvjx8d
  api_key: '226391955645232'
  api_secret: mM68VrokMFI-EzeTwGWh-x9HUnI
  enhance_image_tag: true
  static_file_support: false
